# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  - name: appName
    value: my-app-name 


pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)/target/azure-functions/$(appName)/
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)   
    
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(build.artifactstagingdirectory)'
#     ArtifactName: 'FunctionApp'
#     publishLocation: 'Container'

- publish: $(build.artifactstagingdirectory)
  artifact: FunctionApp

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'

- task: AzureFunctionApp@1
  displayName: Azure Function App deploy
  inputs:
    azureSubscription: 'Content health and performance(82c135d4-f813-4bec-a93e-60e4323918ee)'
    appType: 'functionApp'
    appName: 'my-app-name'
    package: '$(build.artifactstagingdirectory)/$(appName)/**'
    deploymentMethod: 'auto'